blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/Von-Base-Enterprises/core-nexus/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/Von-Base-Enterprises/core-nexus/blob/main/README.md
    about: Check our documentation for setup and usage guides.