# Alertmanager configuration for Core Nexus
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@corenexus.local'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'core-nexus-alerts'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'
    - match:
        severity: info
      receiver: 'info-alerts'

receivers:
  - name: 'core-nexus-alerts'
    webhook_configs:
      - url: 'http://localhost:8080/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://localhost:8080/webhook/critical'
        send_resolved: true
    # Email configuration (uncomment and configure for email alerts)
    # email_configs:
    #   - to: 'admin@yourcompany.com'
    #     subject: 'CRITICAL: Core Nexus Alert'
    #     body: |
    #       {{ range .Alerts }}
    #       Alert: {{ .Annotations.summary }}
    #       Description: {{ .Annotations.description }}
    #       {{ end }}

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://localhost:8080/webhook/warning'
        send_resolved: true

  - name: 'info-alerts'
    webhook_configs:
      - url: 'http://localhost:8080/webhook/info'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']