# Prometheus configuration for Core Nexus Memory Service
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Core Nexus Memory Service (Production)
  - job_name: 'core-nexus-production'
    static_configs:
      - targets: ['CORE_NEXUS_URL:443']
    scheme: https
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Core Nexus Memory Service (Local Development)
  - job_name: 'core-nexus-local'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # UptimeRobot external monitoring (if webhook configured)
  - job_name: 'uptimerobot'
    static_configs:
      - targets: []  # Configure if UptimeRobot webhook available