# Promtail configuration for Core Nexus logs
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: core-nexus-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: core-nexus
          __path__: /var/log/core-nexus/*.log

  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log