# Docker Compose for Core Nexus production stores
# Currently disabled for Day-1 slice (uses JSON + SQLite)
# Uncomment when ready to scale to production

version: '3.8'

services:
  # Vector database for embeddings and similarity search
  # milvus:
  #   image: milvusdb/milvus:v2.3.4
  #   container_name: core_nexus_milvus
  #   ports:
  #     - "19530:19530"
  #     - "9091:9091"
  #   environment:
  #     ETCD_ENDPOINTS: etcd:2379
  #     MINIO_ADDRESS: minio:9000
  #   depends_on:
  #     - etcd
  #     - minio
  #   volumes:
  #     - milvus_data:/var/lib/milvus
  #   networks:
  #     - core_nexus_net

  # Graph database for relationships and context
  # neo4j:
  #   image: neo4j:5.14.0
  #   container_name: core_nexus_neo4j
  #   ports:
  #     - "7474:7474"  # HTTP
  #     - "7687:7687"  # Bolt
  #   environment:
  #     NEO4J_AUTH: neo4j/corenexus2024
  #     NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
  #     NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*"
  #   volumes:
  #     - neo4j_data:/data
  #     - neo4j_logs:/logs
  #   networks:
  #     - core_nexus_net

  # Supporting services for Milvus
  # etcd:
  #   image: quay.io/coreos/etcd:v3.5.5
  #   container_name: core_nexus_etcd
  #   environment:
  #     - ETCD_AUTO_COMPACTION_MODE=revision
  #     - ETCD_AUTO_COMPACTION_RETENTION=1000
  #     - ETCD_QUOTA_BACKEND_BYTES=4294967296
  #   command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
  #   volumes:
  #     - etcd_data:/etcd
  #   networks:
  #     - core_nexus_net

  # minio:
  #   image: minio/minio:RELEASE.2023-03-20T20-16-18Z
  #   container_name: core_nexus_minio
  #   environment:
  #     MINIO_ACCESS_KEY: minioadmin
  #     MINIO_SECRET_KEY: minioadmin
  #   command: minio server /data
  #   volumes:
  #     - minio_data:/data
  #   networks:
  #     - core_nexus_net

# Placeholder for Day-1 slice
# The slice uses local JSON + SQLite files instead
placeholder:
  image: hello-world
  container_name: core_nexus_slice_placeholder
  command: echo "Day-1 slice uses local storage. Uncomment services above for production scaling."

# networks:
#   core_nexus_net:
#     driver: bridge

# volumes:
#   milvus_data:
#   neo4j_data:
#   neo4j_logs:
#   etcd_data:
#   minio_data: